server.port=${PORT:8085}

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=elta

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true